phase_codes = {500:'Standing', 501:'Standing - pre-flight', 502: 'Standing - starting engine(s)',
               503: 'Standing - engine(s) operating', 504:'Standing - engine(s) not operating',
               505: 'Standing - idling rotors', 510: 'Taxi', 511: 'Taxi - pushback/tow', 512: 'Taxi - to takeoff',
               513: 'Taxi - from landing', 514: 'Taxi - aerial', 520:'Takeoff', 521: 'Takeoff - roll/run',
               522: 'Takeoff - initial climb', 523: 'Takeoff - aborted', 530: 'Climb', 531: 'Climb - to cruise',
               540: 'Cruise', 541: 'Cruise - normal', 542: 'Maneuvering - holding (IFR)', 550: 'Descent',
               551: 'Descent - normal', 552: 'Descent - emergency', 553: 'Descent - uncontrolled', 560: 'Approach',
               561: 'Approach - VFR pattern - downwind', 562: 'Approach - VFR pattern - turn to base',
               563: 'Approach - VFR pattern - base leg/base to final', 564: 'Approach - VFR pattern - final approach',
               565: 'Go-around (VFR)', 566: 'Approach - Initial approach fix (IAF) to final approach fix (FAF)/outer marker (IFR)',
               567: 'Approach - final approach fix (FAF)/outer marker to threshold (IFR)',
               568: 'Approach - circling (IFR)', 569: 'Missed approach (IFR)', 570: 'Landing', 571: 'Landing - flare/touchdown',
               572: 'Landing - roll', 573: 'Landing - aborted', 574: 'Emergency landing', 575: 'Emergency landing after takeoff',
               576: 'Emergency descent/landing', 580: 'Maneuvering', 581: 'Maneuvering - aerial application',
               582: 'Maneuvering - turn to reverse direction', 583: 'Maneuvering - turn to landing area (emergency)',
               590: 'Hover', 591: 'Hover - in ground effect', 592: 'Hover - out of ground effect', 600: 'Other', 610:'Unknown',
               0: None}
